class CPU {

    constructor() {
        // Time clock: The Z80 holds two types of clock (m and t)
        this._clock = {m: 0, t:0};
        this._r = {
            a: 0, b: 0, c: 0, d: 0, e: 0, h: 0, l: 0, f: 0, // 8-bit registers
            pc: 0, sp: 0, i: 0, r:0,                        // 16-bit registers
            m: 0, t: 0,                                     // clock for last instr
            ime: 0
        };
        this._halt: 0;
        this._stop: 0;
        this._map = [
            // 00
              this._ops.NOP,
              this._ops.LDBCnn,
              this._ops.LDBCmA,
              this._ops.INCBC,
              this._ops.INCr_b,
              this._ops.DECr_b,
              this._ops.LDrn_b,
              this._ops.RLCA,
              this._ops.LDmmSP,
              this._ops.ADDHLBC,
              this._ops.LDABCm,
              this._ops.DECBC,
              this._ops.INCr_c,
              this._ops.DECr_c,
              this._ops.LDrn_c,
              this._ops.RRCA,

              // 10
              this._ops.DJNZn,
              this._ops.LDDEnn,
              this._ops.LDDEmA,
              this._ops.INCDE,
              this._ops.INCr_d,
              this._ops.DECr_d,
              this._ops.LDrn_d,
              this._ops.RLA,
              this._ops.JRn,
              this._ops.ADDHLDE,
              this._ops.LDADEm,
              this._ops.DECDE,
              this._ops.INCr_e,
              this._ops.DECr_e,
              this._ops.LDrn_e,
              this._ops.RRA,

              // 20
              this._ops.JRNZn,
              this._ops.LDHLnn,
              this._ops.LDHLIA,
              this._ops.INCHL,
              this._ops.INCr_h,
              this._ops.DECr_h,
              this._ops.LDrn_h,
              this._ops.XX,
              this._ops.JRZn,
              this._ops.ADDHLHL,
              this._ops.LDAHLI,
              this._ops.DECHL,
              this._ops.INCr_l,
              this._ops.DECr_l,
              this._ops.LDrn_l,
              this._ops.CPL,

              // 30
              this._ops.JRNCn,
              this._ops.LDSPnn,
              this._ops.LDHLDA,
              this._ops.INCSP,
              this._ops.INCHLm,
              this._ops.DECHLm,
              this._ops.LDHLmn,
              this._ops.SCF,
              this._ops.JRCn,
              this._ops.ADDHLSP,
              this._ops.LDAHLD,
              this._ops.DECSP,
              this._ops.INCr_a,
              this._ops.DECr_a,
              this._ops.LDrn_a,
              this._ops.CCF,

              // 40
              this._ops.LDrr_bb,
              this._ops.LDrr_bc,
              this._ops.LDrr_bd,
              this._ops.LDrr_be,
              this._ops.LDrr_bh,
              this._ops.LDrr_bl,
              this._ops.LDrHLm_b,
              this._ops.LDrr_ba,
              this._ops.LDrr_cb,
              this._ops.LDrr_cc,
              this._ops.LDrr_cd,
              this._ops.LDrr_ce,
              this._ops.LDrr_ch,
              this._ops.LDrr_cl,
              this._ops.LDrHLm_c,
              this._ops.LDrr_ca,

              // 50
              this._ops.LDrr_db,
              this._ops.LDrr_dc,
              this._ops.LDrr_dd,
              this._ops.LDrr_de,
              this._ops.LDrr_dh,
              this._ops.LDrr_dl,
              this._ops.LDrHLm_d,
              this._ops.LDrr_da,
              this._ops.LDrr_eb,
              this._ops.LDrr_ec,
              this._ops.LDrr_ed,
              this._ops.LDrr_ee,
              this._ops.LDrr_eh,
              this._ops.LDrr_el,
              this._ops.LDrHLm_e,
              this._ops.LDrr_ea,

              // 60
              this._ops.LDrr_hb,
              this._ops.LDrr_hc,
              this._ops.LDrr_hd,
              this._ops.LDrr_he,
              this._ops.LDrr_hh,
              this._ops.LDrr_hl,
              this._ops.LDrHLm_h,
              this._ops.LDrr_ha,
              this._ops.LDrr_lb,
              this._ops.LDrr_lc,
              this._ops.LDrr_ld,
              this._ops.LDrr_le,
              this._ops.LDrr_lh,
              this._ops.LDrr_ll,
              this._ops.LDrHLm_l,
              this._ops.LDrr_la,

              // 70
              this._ops.LDHLmr_b,
              this._ops.LDHLmr_c,
              this._ops.LDHLmr_d,
              this._ops.LDHLmr_e,
              this._ops.LDHLmr_h,
              this._ops.LDHLmr_l,
              this._ops.HALT,
              this._ops.LDHLmr_a,
              this._ops.LDrr_ab,
              this._ops.LDrr_ac,
              this._ops.LDrr_ad,
              this._ops.LDrr_ae,
              this._ops.LDrr_ah,
              this._ops.LDrr_al,
              this._ops.LDrHLm_a,
              this._ops.LDrr_aa,

              // 80
              this._ops.ADDr_b,
              this._ops.ADDr_c,
              this._ops.ADDr_d,
              this._ops.ADDr_e,
              this._ops.ADDr_h,
              this._ops.ADDr_l,
              this._ops.ADDHL,
              this._ops.ADDr_a,
              this._ops.ADCr_b,
              this._ops.ADCr_c,
              this._ops.ADCr_d,
              this._ops.ADCr_e,
              this._ops.ADCr_h,
              this._ops.ADCr_l,
              this._ops.ADCHL,
              this._ops.ADCr_a,

              // 90
              this._ops.SUBr_b,
              this._ops.SUBr_c,
              this._ops.SUBr_d,
              this._ops.SUBr_e,
              this._ops.SUBr_h,
              this._ops.SUBr_l,
              this._ops.SUBHL,
              this._ops.SUBr_a,
              this._ops.SBCr_b,
              this._ops.SBCr_c,
              this._ops.SBCr_d,
              this._ops.SBCr_e,
              this._ops.SBCr_h,
              this._ops.SBCr_l,
              this._ops.SBCHL,
              this._ops.SBCr_a,

              // A0
              this._ops.ANDr_b,
              this._ops.ANDr_c,
              this._ops.ANDr_d,
              this._ops.ANDr_e,
              this._ops.ANDr_h,
              this._ops.ANDr_l,
              this._ops.ANDHL,
              this._ops.ANDr_a,
              this._ops.XORr_b,
              this._ops.XORr_c,
              this._ops.XORr_d,
              this._ops.XORr_e,
              this._ops.XORr_h,
              this._ops.XORr_l,
              this._ops.XORHL,
              this._ops.XORr_a,

              // B0
              this._ops.ORr_b,
              this._ops.ORr_c,
              this._ops.ORr_d,
              this._ops.ORr_e,
              this._ops.ORr_h,
              this._ops.ORr_l,
              this._ops.ORHL,
              this._ops.ORr_a,
              this._ops.CPr_b,
              this._ops.CPr_c,
              this._ops.CPr_d,
              this._ops.CPr_e,
              this._ops.CPr_h,
              this._ops.CPr_l,
              this._ops.CPHL,
              this._ops.CPr_a,

              // C0
              this._ops.RETNZ,
              this._ops.POPBC,
              this._ops.JPNZnn,
              this._ops.JPnn,
              this._ops.CALLNZnn,
              this._ops.PUSHBC,
              this._ops.ADDn,
              this._ops.RST00,
              this._ops.RETZ,
              this._ops.RET,
              this._ops.JPZnn,
              this._ops.MAPcb,
              this._ops.CALLZnn,
              this._ops.CALLnn,
              this._ops.ADCn,
              this._ops.RST08,

              // D0
              this._ops.RETNC,
              this._ops.POPDE,
              this._ops.JPNCnn,
              this._ops.XX,
              this._ops.CALLNCnn,
              this._ops.PUSHDE,
              this._ops.SUBn,
              this._ops.RST10,
              this._ops.RETC,
              this._ops.RETI,
              this._ops.JPCnn,
              this._ops.XX,
              this._ops.CALLCnn,
              this._ops.XX,
              this._ops.SBCn,
              this._ops.RST18,

              // E0
              this._ops.LDIOnA,
              this._ops.POPHL,
              this._ops.LDIOCA,
              this._ops.XX,
              this._ops.XX,
              this._ops.PUSHHL,
              this._ops.ANDn,
              this._ops.RST20,
              this._ops.ADDSPn,
              this._ops.JPHL,
              this._ops.LDmmA,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.ORn,
              this._ops.RST28,

              // F0
              this._ops.LDAIOn,
              this._ops.POPAF,
              this._ops.LDAIOC,
              this._ops.DI,
              this._ops.XX,
              this._ops.PUSHAF,
              this._ops.XORn,
              this._ops.RST30,
              this._ops.LDHLSPn,
              this._ops.XX,
              this._ops.LDAmm,
              this._ops.EI,
              this._ops.XX,
              this._ops.XX,
              this._ops.CPn,
              this._ops.RST38
        ];

        this._cbmap = [
            // CB00
              this._ops.RLCr_b,
              this._ops.RLCr_c,
              this._ops.RLCr_d,
              this._ops.RLCr_e,
              this._ops.RLCr_h,
              this._ops.RLCr_l,
              this._ops.RLCHL,
              this._ops.RLCr_a,
              this._ops.RRCr_b,
              this._ops.RRCr_c,
              this._ops.RRCr_d,
              this._ops.RRCr_e,
              this._ops.RRCr_h,
              this._ops.RRCr_l,
              this._ops.RRCHL,
              this._ops.RRCr_a,

              // CB10
              this._ops.RLr_b,
              this._ops.RLr_c,
              this._ops.RLr_d,
              this._ops.RLr_e,
              this._ops.RLr_h,
              this._ops.RLr_l,
              this._ops.RLHL,
              this._ops.RLr_a,
              this._ops.RRr_b,
              this._ops.RRr_c,
              this._ops.RRr_d,
              this._ops.RRr_e,
              this._ops.RRr_h,
              this._ops.RRr_l,
              this._ops.RRHL,
              this._ops.RRr_a,

              // CB20
              this._ops.SLAr_b,
              this._ops.SLAr_c,
              this._ops.SLAr_d,
              this._ops.SLAr_e,
              this._ops.SLAr_h,
              this._ops.SLAr_l,
              this._ops.XX,
              this._ops.SLAr_a,
              this._ops.SRAr_b,
              this._ops.SRAr_c,
              this._ops.SRAr_d,
              this._ops.SRAr_e,
              this._ops.SRAr_h,
              this._ops.SRAr_l,
              this._ops.XX,
              this._ops.SRAr_a,

              // CB30
              this._ops.SWAPr_b,
              this._ops.SWAPr_c,
              this._ops.SWAPr_d,
              this._ops.SWAPr_e,
              this._ops.SWAPr_h,
              this._ops.SWAPr_l,
              this._ops.XX,
              this._ops.SWAPr_a,
              this._ops.SRLr_b,
              this._ops.SRLr_c,
              this._ops.SRLr_d,
              this._ops.SRLr_e,
              this._ops.SRLr_h,
              this._ops.SRLr_l,
              this._ops.XX,
              this._ops.SRLr_a,

              // CB40
              this._ops.BIT0b,
              this._ops.BIT0c,
              this._ops.BIT0d,
              this._ops.BIT0e,
              this._ops.BIT0h,
              this._ops.BIT0l,
              this._ops.BIT0m,
              this._ops.BIT0a,
              this._ops.BIT1b,
              this._ops.BIT1c,
              this._ops.BIT1d,
              this._ops.BIT1e,
              this._ops.BIT1h,
              this._ops.BIT1l,
              this._ops.BIT1m,
              this._ops.BIT1a,

              // CB50
              this._ops.BIT2b,
              this._ops.BIT2c,
              this._ops.BIT2d,
              this._ops.BIT2e,
              this._ops.BIT2h,
              this._ops.BIT2l,
              this._ops.BIT2m,
              this._ops.BIT2a,
              this._ops.BIT3b,
              this._ops.BIT3c,
              this._ops.BIT3d,
              this._ops.BIT3e,
              this._ops.BIT3h,
              this._ops.BIT3l,
              this._ops.BIT3m,
              this._ops.BIT3a,

              // CB60
              this._ops.BIT4b,
              this._ops.BIT4c,
              this._ops.BIT4d,
              this._ops.BIT4e,
              this._ops.BIT4h,
              this._ops.BIT4l,
              this._ops.BIT4m,
              this._ops.BIT4a,
              this._ops.BIT5b,
              this._ops.BIT5c,
              this._ops.BIT5d,
              this._ops.BIT5e,
              this._ops.BIT5h,
              this._ops.BIT5l,
              this._ops.BIT5m,
              this._ops.BIT5a,

              // CB70
              this._ops.BIT6b,
              this._ops.BIT6c,
              this._ops.BIT6d,
              this._ops.BIT6e,
              this._ops.BIT6h,
              this._ops.BIT6l,
              this._ops.BIT6m,
              this._ops.BIT6a,
              this._ops.BIT7b,
              this._ops.BIT7c,
              this._ops.BIT7d,
              this._ops.BIT7e,
              this._ops.BIT7h,
              this._ops.BIT7l,
              this._ops.BIT7m,
              this._ops.BIT7a,

              // CB80
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CB90
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBA0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBB0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBC0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBD0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBE0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,

              // CBF0
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX,
              this._ops.XX
        ]

        this._ops = {
            /*--- Load/store ---*/
            LDrr_bb: function() { this._r.b=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_bc: function() { this._r.b=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_bd: function() { this._r.b=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_be: function() { this._r.b=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_bh: function() { this._r.b=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_bl: function() { this._r.b=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_ba: function() { this._r.b=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_cb: function() { this._r.c=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_cc: function() { this._r.c=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_cd: function() { this._r.c=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_ce: function() { this._r.c=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_ch: function() { this._r.c=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_cl: function() { this._r.c=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_ca: function() { this._r.c=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_db: function() { this._r.d=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_dc: function() { this._r.d=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_dd: function() { this._r.d=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_de: function() { this._r.d=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_dh: function() { this._r.d=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_dl: function() { this._r.d=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_da: function() { this._r.d=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_eb: function() { this._r.e=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_ec: function() { this._r.e=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_ed: function() { this._r.e=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_ee: function() { this._r.e=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_eh: function() { this._r.e=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_el: function() { this._r.e=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_ea: function() { this._r.e=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_hb: function() { this._r.h=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_hc: function() { this._r.h=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_hd: function() { this._r.h=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_he: function() { this._r.h=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_hh: function() { this._r.h=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_hl: function() { this._r.h=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_ha: function() { this._r.h=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_lb: function() { this._r.l=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_lc: function() { this._r.l=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_ld: function() { this._r.l=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_le: function() { this._r.l=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_lh: function() { this._r.l=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_ll: function() { this._r.l=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_la: function() { this._r.l=this._r.a; this._r.m=1; this._r.t=4; },
            LDrr_ab: function() { this._r.a=this._r.b; this._r.m=1; this._r.t=4; },
            LDrr_ac: function() { this._r.a=this._r.c; this._r.m=1; this._r.t=4; },
            LDrr_ad: function() { this._r.a=this._r.d; this._r.m=1; this._r.t=4; },
            LDrr_ae: function() { this._r.a=this._r.e; this._r.m=1; this._r.t=4; },
            LDrr_ah: function() { this._r.a=this._r.h; this._r.m=1; this._r.t=4; },
            LDrr_al: function() { this._r.a=this._r.l; this._r.m=1; this._r.t=4; },
            LDrr_aa: function() { this._r.a=this._r.a; this._r.m=1; this._r.t=4; },

            LDrHLm_b: function() { this._r.b=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_c: function() { this._r.c=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_d: function() { this._r.d=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_e: function() { this._r.e=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_h: function() { this._r.h=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_l: function() { this._r.l=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },
            LDrHLm_a: function() { this._r.a=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.m=2; this._r.t=8; },

            LDHLmr_b: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.b); this._r.m=2; this._r.t=8; },
            LDHLmr_c: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.c); this._r.m=2; this._r.t=8; },
            LDHLmr_d: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.d); this._r.m=2; this._r.t=8; },
            LDHLmr_e: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.e); this._r.m=2; this._r.t=8; },
            LDHLmr_h: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.h); this._r.m=2; this._r.t=8; },
            LDHLmr_l: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.l); this._r.m=2; this._r.t=8; },
            LDHLmr_a: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l,this._r.a); this._r.m=2; this._r.t=8; },

            LDrn_b: function() { this._r.b=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_c: function() { this._r.c=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_d: function() { this._r.d=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_e: function() { this._r.e=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_h: function() { this._r.h=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_l: function() { this._r.l=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },
            LDrn_a: function() { this._r.a=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.m=2; this._r.t=8; },

            LDHLmn: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l, MemoryInterfacing.rb(this._r.pc)); this._r.pc++; this._r.m=3; this._r.t=12; },

            LDBCmA: function() { MemoryInterfacing.wb((this._r.b<<8)+this._r.c, this._r.a); this._r.m=2; this._r.t=8; },
            LDDEmA: function() { MemoryInterfacing.wb((this._r.d<<8)+this._r.e, this._r.a); this._r.m=2; this._r.t=8; },

            LDmmA: function() { MemoryInterfacing.wb(MemoryInterfacing.rw(this._r.pc), this._r.a); this._r.pc+=2; this._r.m=4; this._r.t=16; },

            LDABCm: function() { this._r.a=MemoryInterfacing.rb((this._r.b<<8)+this._r.c); this._r.m=2; this._r.t=8; },
            LDADEm: function() { this._r.a=MemoryInterfacing.rb((this._r.d<<8)+this._r.e); this._r.m=2; this._r.t=8; },

            LDAmm: function() { this._r.a=MemoryInterfacing.rb(MemoryInterfacing.rw(this._r.pc)); this._r.pc+=2; this._r.m=4; this._r.t=16; },

            LDBCnn: function() { this._r.c=MemoryInterfacing.rb(this._r.pc); this._r.b=MemoryInterfacing.rb(this._r.pc+1); this._r.pc+=2; this._r.m=3; this._r.t=12; },
            LDDEnn: function() { this._r.e=MemoryInterfacing.rb(this._r.pc); this._r.d=MemoryInterfacing.rb(this._r.pc+1); this._r.pc+=2; this._r.m=3; this._r.t=12; },
            LDHLnn: function() { this._r.l=MemoryInterfacing.rb(this._r.pc); this._r.h=MemoryInterfacing.rb(this._r.pc+1); this._r.pc+=2; this._r.m=3; this._r.t=12; },
            LDSPnn: function() { this._r.sp=MemoryInterfacing.rw(this._r.pc); this._r.pc+=2; this._r.m=3; this._r.t=12; },

            LDHLmm: function() { let i=MemoryInterfacing.rw(this._r.pc); this._r.pc+=2; this._r.l=MemoryInterfacing.rb(i); this._r.h=MemoryInterfacing.rb(i+1); this._r.m=5; this._r.t=20; },
            LDmmHL: function() { let i=MemoryInterfacing.rw(this._r.pc); this._r.pc+=2; MemoryInterfacing.ww(i,(this._r.h<<8)+this._r.l); this._r.m=5; this._r.t=20; },

            LDHLIA: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l, this._r.a); this._r.l=(this._r.l+1)&255; if(!this._r.l) this._r.h=(this._r.h+1)&255; this._r.m=2; this._r.t=8; },
            LDAHLI: function() { this._r.a=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.l=(this._r.l+1)&255; if(!this._r.l) this._r.h=(this._r.h+1)&255; this._r.m=2; this._r.t=8; },

            LDHLDA: function() { MemoryInterfacing.wb((this._r.h<<8)+this._r.l, this._r.a); this._r.l=(this._r.l-1)&255; if(this._r.l==255) this._r.h=(this._r.h-1)&255; this._r.m=2; this._r.t=8; },
            LDAHLD: function() { this._r.a=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.l=(this._r.l-1)&255; if(this._r.l==255) this._r.h=(this._r.h-1)&255; this._r.m=2; this._r.t=8; },

            LDAIOn: function() { this._r.a=MemoryInterfacing.rb(0xFF00+MemoryInterfacing.rb(this._r.pc)); this._r.pc++; this._r.m=3; this._r.t=12; },
            LDIOnA: function() { MemoryInterfacing.wb(0xFF00+MemoryInterfacing.rb(this._r.pc),this._r.a); this._r.pc++; this._r.m=3; this._r.t=12; },
            LDAIOC: function() { this._r.a=MemoryInterfacing.rb(0xFF00+this._r.c); this._r.m=2; this._r.t=8; },
            LDIOCA: function() { MemoryInterfacing.wb(0xFF00+this._r.c,this._r.a); this._r.m=2; this._r.t=8; },

            LDHLSPn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; i+=this._r.sp; this._r.h=(i>>8)&255; this._r.l=i&255; this._r.m=3; this._r.t=12; },

            SWAPr_b: function() { let tr=this._r.b; this._r.b=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_c: function() { let tr=this._r.c; this._r.c=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_d: function() { let tr=this._r.d; this._r.d=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_e: function() { let tr=this._r.e; this._r.e=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_h: function() { let tr=this._r.h; this._r.h=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_l: function() { let tr=this._r.l; this._r.l=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },
            SWAPr_a: function() { let tr=this._r.a; this._r.a=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,tr); this._r.m=4; this._r.t=16; },

            /*--- Data processing ---*/
            ADDr_b: function() { this._r.a+=this._r.b; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_c: function() { this._r.a+=this._r.c; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_d: function() { this._r.a+=this._r.d; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_e: function() { this._r.a+=this._r.e; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_h: function() { this._r.a+=this._r.h; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_l: function() { this._r.a+=this._r.l; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDr_a: function() { this._r.a+=this._r.a; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADDHL: function() { this._r.a+=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },
            ADDn: function() { this._r.a+=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },
            ADDHLBC: function() { let hl=(this._r.h<<8)+this._r.l; hl+=(this._r.b<<8)+this._r.c; if(hl>65535) this._r.f|=0x10; else this._r.f&=0xEF; this._r.h=(hl>>8)&255; this._r.l=hl&255; this._r.m=3; this._r.t=12; },
            ADDHLDE: function() { let hl=(this._r.h<<8)+this._r.l; hl+=(this._r.d<<8)+this._r.e; if(hl>65535) this._r.f|=0x10; else this._r.f&=0xEF; this._r.h=(hl>>8)&255; this._r.l=hl&255; this._r.m=3; this._r.t=12; },
            ADDHLHL: function() { let hl=(this._r.h<<8)+this._r.l; hl+=(this._r.h<<8)+this._r.l; if(hl>65535) this._r.f|=0x10; else this._r.f&=0xEF; this._r.h=(hl>>8)&255; this._r.l=hl&255; this._r.m=3; this._r.t=12; },
            ADDHLSP: function() { let hl=(this._r.h<<8)+this._r.l; hl+=this._r.sp; if(hl>65535) this._r.f|=0x10; else this._r.f&=0xEF; this._r.h=(hl>>8)&255; this._r.l=hl&255; this._r.m=3; this._r.t=12; },
            ADDSPn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.sp+=i; this._r.m=4; this._r.t=16; },

            ADCr_b: function() { this._r.a+=this._r.b; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_c: function() { this._r.a+=this._r.c; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_d: function() { this._r.a+=this._r.d; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_e: function() { this._r.a+=this._r.e; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_h: function() { this._r.a+=this._r.h; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_l: function() { this._r.a+=this._r.l; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCr_a: function() { this._r.a+=this._r.a; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            ADCHL: function() { this._r.a+=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },
            ADCn: function() { this._r.a+=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.a+=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a); if(this._r.a>255) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },

            SUBr_b: function() { this._r.a-=this._r.b; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_c: function() { this._r.a-=this._r.c; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_d: function() { this._r.a-=this._r.d; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_e: function() { this._r.a-=this._r.e; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_h: function() { this._r.a-=this._r.h; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_l: function() { this._r.a-=this._r.l; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBr_a: function() { this._r.a-=this._r.a; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SUBHL: function() { this._r.a-=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },
            SUBn: function() { this._r.a-=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },

            SBCr_b: function() { this._r.a-=this._r.b; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_c: function() { this._r.a-=this._r.c; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_d: function() { this._r.a-=this._r.d; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_e: function() { this._r.a-=this._r.e; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_h: function() { this._r.a-=this._r.h; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_l: function() { this._r.a-=this._r.l; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCr_a: function() { this._r.a-=this._r.a; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=1; this._r.t=4; },
            SBCHL: function() { this._r.a-=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },
            SBCn: function() { this._r.a-=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.a-=(this._r.f&0x10)?1:0; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },

            CPr_b: function() { let i=this._r.a; i-=this._r.b; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_c: function() { let i=this._r.a; i-=this._r.c; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_d: function() { let i=this._r.a; i-=this._r.d; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_e: function() { let i=this._r.a; i-=this._r.e; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_h: function() { let i=this._r.a; i-=this._r.h; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_l: function() { let i=this._r.a; i-=this._r.l; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPr_a: function() { let i=this._r.a; i-=this._r.a; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=1; this._r.t=4; },
            CPHL: function() { let i=this._r.a; i-=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=2; this._r.t=8; },
            CPn: function() { let i=this._r.a; i-=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._ops.fz(i,1); if(i<0) this._r.f|=0x10; i&=255; this._r.m=2; this._r.t=8; },

            ANDr_b: function() { this._r.a&=this._r.b; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_c: function() { this._r.a&=this._r.c; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_d: function() { this._r.a&=this._r.d; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_e: function() { this._r.a&=this._r.e; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_h: function() { this._r.a&=this._r.h; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_l: function() { this._r.a&=this._r.l; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDr_a: function() { this._r.a&=this._r.a; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ANDHL: function() { this._r.a&=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },
            ANDn: function() { this._r.a&=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },

            ORr_b: function() { this._r.a|=this._r.b; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_c: function() { this._r.a|=this._r.c; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_d: function() { this._r.a|=this._r.d; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_e: function() { this._r.a|=this._r.e; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_h: function() { this._r.a|=this._r.h; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_l: function() { this._r.a|=this._r.l; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORr_a: function() { this._r.a|=this._r.a; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            ORHL: function() { this._r.a|=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },
            ORn: function() { this._r.a|=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },

            XORr_b: function() { this._r.a^=this._r.b; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_c: function() { this._r.a^=this._r.c; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_d: function() { this._r.a^=this._r.d; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_e: function() { this._r.a^=this._r.e; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_h: function() { this._r.a^=this._r.h; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_l: function() { this._r.a^=this._r.l; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORr_a: function() { this._r.a^=this._r.a; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            XORHL: function() { this._r.a^=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },
            XORn: function() { this._r.a^=MemoryInterfacing.rb(this._r.pc); this._r.pc++; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=2; this._r.t=8; },

            INCr_b: function() { this._r.b++; this._r.b&=255; this._ops.fz(this._r.b); this._r.m=1; this._r.t=4; },
            INCr_c: function() { this._r.c++; this._r.c&=255; this._ops.fz(this._r.c); this._r.m=1; this._r.t=4; },
            INCr_d: function() { this._r.d++; this._r.d&=255; this._ops.fz(this._r.d); this._r.m=1; this._r.t=4; },
            INCr_e: function() { this._r.e++; this._r.e&=255; this._ops.fz(this._r.e); this._r.m=1; this._r.t=4; },
            INCr_h: function() { this._r.h++; this._r.h&=255; this._ops.fz(this._r.h); this._r.m=1; this._r.t=4; },
            INCr_l: function() { this._r.l++; this._r.l&=255; this._ops.fz(this._r.l); this._r.m=1; this._r.t=4; },
            INCr_a: function() { this._r.a++; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            INCHLm: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l)+1; i&=255; MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._ops.fz(i); this._r.m=3; this._r.t=12; },

            DECr_b: function() { this._r.b--; this._r.b&=255; this._ops.fz(this._r.b); this._r.m=1; this._r.t=4; },
            DECr_c: function() { this._r.c--; this._r.c&=255; this._ops.fz(this._r.c); this._r.m=1; this._r.t=4; },
            DECr_d: function() { this._r.d--; this._r.d&=255; this._ops.fz(this._r.d); this._r.m=1; this._r.t=4; },
            DECr_e: function() { this._r.e--; this._r.e&=255; this._ops.fz(this._r.e); this._r.m=1; this._r.t=4; },
            DECr_h: function() { this._r.h--; this._r.h&=255; this._ops.fz(this._r.h); this._r.m=1; this._r.t=4; },
            DECr_l: function() { this._r.l--; this._r.l&=255; this._ops.fz(this._r.l); this._r.m=1; this._r.t=4; },
            DECr_a: function() { this._r.a--; this._r.a&=255; this._ops.fz(this._r.a); this._r.m=1; this._r.t=4; },
            DECHLm: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l)-1; i&=255; MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._ops.fz(i); this._r.m=3; this._r.t=12; },

            INCBC: function() { this._r.c=(this._r.c+1)&255; if(!this._r.c) this._r.b=(this._r.b+1)&255; this._r.m=1; this._r.t=4; },
            INCDE: function() { this._r.e=(this._r.e+1)&255; if(!this._r.e) this._r.d=(this._r.d+1)&255; this._r.m=1; this._r.t=4; },
            INCHL: function() { this._r.l=(this._r.l+1)&255; if(!this._r.l) this._r.h=(this._r.h+1)&255; this._r.m=1; this._r.t=4; },
            INCSP: function() { this._r.sp=(this._r.sp+1)&65535; this._r.m=1; this._r.t=4; },

            DECBC: function() { this._r.c=(this._r.c-1)&255; if(this._r.c==255) this._r.b=(this._r.b-1)&255; this._r.m=1; this._r.t=4; },
            DECDE: function() { this._r.e=(this._r.e-1)&255; if(this._r.e==255) this._r.d=(this._r.d-1)&255; this._r.m=1; this._r.t=4; },
            DECHL: function() { this._r.l=(this._r.l-1)&255; if(this._r.l==255) this._r.h=(this._r.h-1)&255; this._r.m=1; this._r.t=4; },
            DECSP: function() { this._r.sp=(this._r.sp-1)&65535; this._r.m=1; this._r.t=4; },

            /*--- Bit manipulation ---*/
            BIT0b: function() { this._ops.fz(this._r.b&0x01); this._r.m=2; this._r.t=8; },
            BIT0c: function() { this._ops.fz(this._r.c&0x01); this._r.m=2; this._r.t=8; },
            BIT0d: function() { this._ops.fz(this._r.d&0x01); this._r.m=2; this._r.t=8; },
            BIT0e: function() { this._ops.fz(this._r.e&0x01); this._r.m=2; this._r.t=8; },
            BIT0h: function() { this._ops.fz(this._r.h&0x01); this._r.m=2; this._r.t=8; },
            BIT0l: function() { this._ops.fz(this._r.l&0x01); this._r.m=2; this._r.t=8; },
            BIT0a: function() { this._ops.fz(this._r.a&0x01); this._r.m=2; this._r.t=8; },
            BIT0m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x01); this._r.m=3; this._r.t=12; },

            BIT1b: function() { this._ops.fz(this._r.b&0x02); this._r.m=2; this._r.t=8; },
            BIT1c: function() { this._ops.fz(this._r.c&0x02); this._r.m=2; this._r.t=8; },
            BIT1d: function() { this._ops.fz(this._r.d&0x02); this._r.m=2; this._r.t=8; },
            BIT1e: function() { this._ops.fz(this._r.e&0x02); this._r.m=2; this._r.t=8; },
            BIT1h: function() { this._ops.fz(this._r.h&0x02); this._r.m=2; this._r.t=8; },
            BIT1l: function() { this._ops.fz(this._r.l&0x02); this._r.m=2; this._r.t=8; },
            BIT1a: function() { this._ops.fz(this._r.a&0x02); this._r.m=2; this._r.t=8; },
            BIT1m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x02); this._r.m=3; this._r.t=12; },

            BIT2b: function() { this._ops.fz(this._r.b&0x04); this._r.m=2; this._r.t=8; },
            BIT2c: function() { this._ops.fz(this._r.c&0x04); this._r.m=2; this._r.t=8; },
            BIT2d: function() { this._ops.fz(this._r.d&0x04); this._r.m=2; this._r.t=8; },
            BIT2e: function() { this._ops.fz(this._r.e&0x04); this._r.m=2; this._r.t=8; },
            BIT2h: function() { this._ops.fz(this._r.h&0x04); this._r.m=2; this._r.t=8; },
            BIT2l: function() { this._ops.fz(this._r.l&0x04); this._r.m=2; this._r.t=8; },
            BIT2a: function() { this._ops.fz(this._r.a&0x04); this._r.m=2; this._r.t=8; },
            BIT2m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x04); this._r.m=3; this._r.t=12; },

            BIT3b: function() { this._ops.fz(this._r.b&0x08); this._r.m=2; this._r.t=8; },
            BIT3c: function() { this._ops.fz(this._r.c&0x08); this._r.m=2; this._r.t=8; },
            BIT3d: function() { this._ops.fz(this._r.d&0x08); this._r.m=2; this._r.t=8; },
            BIT3e: function() { this._ops.fz(this._r.e&0x08); this._r.m=2; this._r.t=8; },
            BIT3h: function() { this._ops.fz(this._r.h&0x08); this._r.m=2; this._r.t=8; },
            BIT3l: function() { this._ops.fz(this._r.l&0x08); this._r.m=2; this._r.t=8; },
            BIT3a: function() { this._ops.fz(this._r.a&0x08); this._r.m=2; this._r.t=8; },
            BIT3m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x08); this._r.m=3; this._r.t=12; },

            BIT4b: function() { this._ops.fz(this._r.b&0x10); this._r.m=2; this._r.t=8; },
            BIT4c: function() { this._ops.fz(this._r.c&0x10); this._r.m=2; this._r.t=8; },
            BIT4d: function() { this._ops.fz(this._r.d&0x10); this._r.m=2; this._r.t=8; },
            BIT4e: function() { this._ops.fz(this._r.e&0x10); this._r.m=2; this._r.t=8; },
            BIT4h: function() { this._ops.fz(this._r.h&0x10); this._r.m=2; this._r.t=8; },
            BIT4l: function() { this._ops.fz(this._r.l&0x10); this._r.m=2; this._r.t=8; },
            BIT4a: function() { this._ops.fz(this._r.a&0x10); this._r.m=2; this._r.t=8; },
            BIT4m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x10); this._r.m=3; this._r.t=12; },

            BIT5b: function() { this._ops.fz(this._r.b&0x20); this._r.m=2; this._r.t=8; },
            BIT5c: function() { this._ops.fz(this._r.c&0x20); this._r.m=2; this._r.t=8; },
            BIT5d: function() { this._ops.fz(this._r.d&0x20); this._r.m=2; this._r.t=8; },
            BIT5e: function() { this._ops.fz(this._r.e&0x20); this._r.m=2; this._r.t=8; },
            BIT5h: function() { this._ops.fz(this._r.h&0x20); this._r.m=2; this._r.t=8; },
            BIT5l: function() { this._ops.fz(this._r.l&0x20); this._r.m=2; this._r.t=8; },
            BIT5a: function() { this._ops.fz(this._r.a&0x20); this._r.m=2; this._r.t=8; },
            BIT5m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x20); this._r.m=3; this._r.t=12; },

            BIT6b: function() { this._ops.fz(this._r.b&0x40); this._r.m=2; this._r.t=8; },
            BIT6c: function() { this._ops.fz(this._r.c&0x40); this._r.m=2; this._r.t=8; },
            BIT6d: function() { this._ops.fz(this._r.d&0x40); this._r.m=2; this._r.t=8; },
            BIT6e: function() { this._ops.fz(this._r.e&0x40); this._r.m=2; this._r.t=8; },
            BIT6h: function() { this._ops.fz(this._r.h&0x40); this._r.m=2; this._r.t=8; },
            BIT6l: function() { this._ops.fz(this._r.l&0x40); this._r.m=2; this._r.t=8; },
            BIT6a: function() { this._ops.fz(this._r.a&0x40); this._r.m=2; this._r.t=8; },
            BIT6m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x40); this._r.m=3; this._r.t=12; },

            BIT7b: function() { this._ops.fz(this._r.b&0x80); this._r.m=2; this._r.t=8; },
            BIT7c: function() { this._ops.fz(this._r.c&0x80); this._r.m=2; this._r.t=8; },
            BIT7d: function() { this._ops.fz(this._r.d&0x80); this._r.m=2; this._r.t=8; },
            BIT7e: function() { this._ops.fz(this._r.e&0x80); this._r.m=2; this._r.t=8; },
            BIT7h: function() { this._ops.fz(this._r.h&0x80); this._r.m=2; this._r.t=8; },
            BIT7l: function() { this._ops.fz(this._r.l&0x80); this._r.m=2; this._r.t=8; },
            BIT7a: function() { this._ops.fz(this._r.a&0x80); this._r.m=2; this._r.t=8; },
            BIT7m: function() { this._ops.fz(MemoryInterfacing.rb((this._r.h<<8)+this._r.l)&0x80); this._r.m=3; this._r.t=12; },

            RLA: function() { let ci=this._r.f&0x10?1:0; let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)+ci; this._r.a&=255; this._r.f=(this._r.f&0xEF)+co; this._r.m=1; this._r.t=4; },
            RLCA: function() { let ci=this._r.a&0x80?1:0; let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)+ci; this._r.a&=255; this._r.f=(this._r.f&0xEF)+co; this._r.m=1; this._r.t=4; },
            RRA: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.a&1?0x10:0; this._r.a=(this._r.a>>1)+ci; this._r.a&=255; this._r.f=(this._r.f&0xEF)+co; this._r.m=1; this._r.t=4; },
            RRCA: function() { let ci=this._r.a&1?0x80:0; let co=this._r.a&1?0x10:0; this._r.a=(this._r.a>>1)+ci; this._r.a&=255; this._r.f=(this._r.f&0xEF)+co; this._r.m=1; this._r.t=4; },

            RLr_b: function() { let ci=this._r.f&0x10?1:0; let co=this._r.b&0x80?0x10:0; this._r.b=(this._r.b<<1)+ci; this._r.b&=255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_c: function() { let ci=this._r.f&0x10?1:0; let co=this._r.c&0x80?0x10:0; this._r.c=(this._r.c<<1)+ci; this._r.c&=255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_d: function() { let ci=this._r.f&0x10?1:0; let co=this._r.d&0x80?0x10:0; this._r.d=(this._r.d<<1)+ci; this._r.d&=255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_e: function() { let ci=this._r.f&0x10?1:0; let co=this._r.e&0x80?0x10:0; this._r.e=(this._r.e<<1)+ci; this._r.e&=255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_h: function() { let ci=this._r.f&0x10?1:0; let co=this._r.h&0x80?0x10:0; this._r.h=(this._r.h<<1)+ci; this._r.h&=255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_l: function() { let ci=this._r.f&0x10?1:0; let co=this._r.l&0x80?0x10:0; this._r.l=(this._r.l<<1)+ci; this._r.l&=255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLr_a: function() { let ci=this._r.f&0x10?1:0; let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)+ci; this._r.a&=255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLHL: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); let ci=this._r.f&0x10?1:0; let co=i&0x80?0x10:0; i=(i<<1)+ci; i&=255; this._ops.fz(i); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._r.f=(this._r.f&0xEF)+co; this._r.m=4; this._r.t=16; },

            RLCr_b: function() { let ci=this._r.b&0x80?1:0; let co=this._r.b&0x80?0x10:0; this._r.b=(this._r.b<<1)+ci; this._r.b&=255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_c: function() { let ci=this._r.c&0x80?1:0; let co=this._r.c&0x80?0x10:0; this._r.c=(this._r.c<<1)+ci; this._r.c&=255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_d: function() { let ci=this._r.d&0x80?1:0; let co=this._r.d&0x80?0x10:0; this._r.d=(this._r.d<<1)+ci; this._r.d&=255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_e: function() { let ci=this._r.e&0x80?1:0; let co=this._r.e&0x80?0x10:0; this._r.e=(this._r.e<<1)+ci; this._r.e&=255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_h: function() { let ci=this._r.h&0x80?1:0; let co=this._r.h&0x80?0x10:0; this._r.h=(this._r.h<<1)+ci; this._r.h&=255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_l: function() { let ci=this._r.l&0x80?1:0; let co=this._r.l&0x80?0x10:0; this._r.l=(this._r.l<<1)+ci; this._r.l&=255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCr_a: function() { let ci=this._r.a&0x80?1:0; let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)+ci; this._r.a&=255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RLCHL: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); let ci=i&0x80?1:0; let co=i&0x80?0x10:0; i=(i<<1)+ci; i&=255; this._ops.fz(i); MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._r.f=(this._r.f&0xEF)+co; this._r.m=4; this._r.t=16; },

            RRr_b: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.b&1?0x10:0; this._r.b=(this._r.b>>1)+ci; this._r.b&=255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_c: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.c&1?0x10:0; this._r.c=(this._r.c>>1)+ci; this._r.c&=255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_d: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.d&1?0x10:0; this._r.d=(this._r.d>>1)+ci; this._r.d&=255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_e: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.e&1?0x10:0; this._r.e=(this._r.e>>1)+ci; this._r.e&=255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_h: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.h&1?0x10:0; this._r.h=(this._r.h>>1)+ci; this._r.h&=255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_l: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.l&1?0x10:0; this._r.l=(this._r.l>>1)+ci; this._r.l&=255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRr_a: function() { let ci=this._r.f&0x10?0x80:0; let co=this._r.a&1?0x10:0; this._r.a=(this._r.a>>1)+ci; this._r.a&=255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRHL: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); let ci=this._r.f&0x10?0x80:0; let co=i&1?0x10:0; i=(i>>1)+ci; i&=255; MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._ops.fz(i); this._r.f=(this._r.f&0xEF)+co; this._r.m=4; this._r.t=16; },

            RRCr_b: function() { let ci=this._r.b&1?0x80:0; let co=this._r.b&1?0x10:0; this._r.b=(this._r.b>>1)+ci; this._r.b&=255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_c: function() { let ci=this._r.c&1?0x80:0; let co=this._r.c&1?0x10:0; this._r.c=(this._r.c>>1)+ci; this._r.c&=255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_d: function() { let ci=this._r.d&1?0x80:0; let co=this._r.d&1?0x10:0; this._r.d=(this._r.d>>1)+ci; this._r.d&=255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_e: function() { let ci=this._r.e&1?0x80:0; let co=this._r.e&1?0x10:0; this._r.e=(this._r.e>>1)+ci; this._r.e&=255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_h: function() { let ci=this._r.h&1?0x80:0; let co=this._r.h&1?0x10:0; this._r.h=(this._r.h>>1)+ci; this._r.h&=255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_l: function() { let ci=this._r.l&1?0x80:0; let co=this._r.l&1?0x10:0; this._r.l=(this._r.l>>1)+ci; this._r.l&=255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCr_a: function() { let ci=this._r.a&1?0x80:0; let co=this._r.a&1?0x10:0; this._r.a=(this._r.a>>1)+ci; this._r.a&=255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            RRCHL: function() { let i=MemoryInterfacing.rb((this._r.h<<8)+this._r.l); let ci=i&1?0x80:0; let co=i&1?0x10:0; i=(i>>1)+ci; i&=255; MemoryInterfacing.wb((this._r.h<<8)+this._r.l,i); this._ops.fz(i); this._r.f=(this._r.f&0xEF)+co; this._r.m=4; this._r.t=16; },

            SLAr_b: function() { let co=this._r.b&0x80?0x10:0; this._r.b=(this._r.b<<1)&255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_c: function() { let co=this._r.c&0x80?0x10:0; this._r.c=(this._r.c<<1)&255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_d: function() { let co=this._r.d&0x80?0x10:0; this._r.d=(this._r.d<<1)&255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_e: function() { let co=this._r.e&0x80?0x10:0; this._r.e=(this._r.e<<1)&255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_h: function() { let co=this._r.h&0x80?0x10:0; this._r.h=(this._r.h<<1)&255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_l: function() { let co=this._r.l&0x80?0x10:0; this._r.l=(this._r.l<<1)&255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLAr_a: function() { let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)&255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },

            SLLr_b: function() { let co=this._r.b&0x80?0x10:0; this._r.b=(this._r.b<<1)&255+1; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_c: function() { let co=this._r.c&0x80?0x10:0; this._r.c=(this._r.c<<1)&255+1; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_d: function() { let co=this._r.d&0x80?0x10:0; this._r.d=(this._r.d<<1)&255+1; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_e: function() { let co=this._r.e&0x80?0x10:0; this._r.e=(this._r.e<<1)&255+1; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_h: function() { let co=this._r.h&0x80?0x10:0; this._r.h=(this._r.h<<1)&255+1; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_l: function() { let co=this._r.l&0x80?0x10:0; this._r.l=(this._r.l<<1)&255+1; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SLLr_a: function() { let co=this._r.a&0x80?0x10:0; this._r.a=(this._r.a<<1)&255+1; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },

            SRAr_b: function() { let ci=this._r.b&0x80; let co=this._r.b&1?0x10:0; this._r.b=((this._r.b>>1)+ci)&255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_c: function() { let ci=this._r.c&0x80; let co=this._r.c&1?0x10:0; this._r.c=((this._r.c>>1)+ci)&255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_d: function() { let ci=this._r.d&0x80; let co=this._r.d&1?0x10:0; this._r.d=((this._r.d>>1)+ci)&255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_e: function() { let ci=this._r.e&0x80; let co=this._r.e&1?0x10:0; this._r.e=((this._r.e>>1)+ci)&255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_h: function() { let ci=this._r.h&0x80; let co=this._r.h&1?0x10:0; this._r.h=((this._r.h>>1)+ci)&255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_l: function() { let ci=this._r.l&0x80; let co=this._r.l&1?0x10:0; this._r.l=((this._r.l>>1)+ci)&255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRAr_a: function() { let ci=this._r.a&0x80; let co=this._r.a&1?0x10:0; this._r.a=((this._r.a>>1)+ci)&255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },

            SRLr_b: function() { let co=this._r.b&1?0x10:0; this._r.b=(this._r.b>>1)&255; this._ops.fz(this._r.b); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_c: function() { let co=this._r.c&1?0x10:0; this._r.c=(this._r.c>>1)&255; this._ops.fz(this._r.c); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_d: function() { let co=this._r.d&1?0x10:0; this._r.d=(this._r.d>>1)&255; this._ops.fz(this._r.d); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_e: function() { let co=this._r.e&1?0x10:0; this._r.e=(this._r.e>>1)&255; this._ops.fz(this._r.e); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_h: function() { let co=this._r.h&1?0x10:0; this._r.h=(this._r.h>>1)&255; this._ops.fz(this._r.h); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_l: function() { let co=this._r.l&1?0x10:0; this._r.l=(this._r.l>>1)&255; this._ops.fz(this._r.l); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },
            SRLr_a: function() { let co=this._r.a&1?0x10:0; this._r.a=(this._r.a>>1)&255; this._ops.fz(this._r.a); this._r.f=(this._r.f&0xEF)+co; this._r.m=2; this._r.t=8; },

            CPL: function() { this._r.a = (~this._r.a)&255; this._ops.fz(this._r.a,1); this._r.m=1; this._r.t=4; },
            NEG: function() { this._r.a=0-this._r.a; this._ops.fz(this._r.a,1); if(this._r.a<0) this._r.f|=0x10; this._r.a&=255; this._r.m=2; this._r.t=8; },

            CCF: function() { let ci=this._r.f&0x10?0:0x10; this._r.f=(this._r.f&0xEF)+ci; this._r.m=1; this._r.t=4; },
            SCF: function() { this._r.f|=0x10; this._r.m=1; this._r.t=4; },

            /*--- Stack ---*/
            PUSHBC: function() { this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.b); this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.c); this._r.m=3; this._r.t=12; },
            PUSHDE: function() { this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.d); this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.e); this._r.m=3; this._r.t=12; },
            PUSHHL: function() { this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.h); this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.l); this._r.m=3; this._r.t=12; },
            PUSHAF: function() { this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.a); this._r.sp--; MemoryInterfacing.wb(this._r.sp,this._r.f); this._r.m=3; this._r.t=12; },

            POPBC: function() { this._r.c=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.b=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.m=3; this._r.t=12; },
            POPDE: function() { this._r.e=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.d=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.m=3; this._r.t=12; },
            POPHL: function() { this._r.l=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.h=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.m=3; this._r.t=12; },
            POPAF: function() { this._r.f=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.a=MemoryInterfacing.rb(this._r.sp); this._r.sp++; this._r.m=3; this._r.t=12; },

            /*--- Jump ---*/
            JPnn: function() { this._r.pc = MemoryInterfacing.rw(this._r.pc); this._r.m=3; this._r.t=12; },
            JPHL: function() { this._r.pc=this._r.hl; this._r.m=1; this._r.t=4; },
            JPNZnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x80)==0x00) { this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m++; this._r.t+=4; } else this._r.pc+=2; },
            JPZnn: function()  { this._r.m=3; this._r.t=12; if((this._r.f&0x80)==0x80) { this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m++; this._r.t+=4; } else this._r.pc+=2; },
            JPNCnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x10)==0x00) { this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m++; this._r.t+=4; } else this._r.pc+=2; },
            JPCnn: function()  { this._r.m=3; this._r.t=12; if((this._r.f&0x10)==0x10) { this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m++; this._r.t+=4; } else this._r.pc+=2; },

            JRn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; this._r.pc+=i; this._r.m++; this._r.t+=4; },
            JRNZn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; if((this._r.f&0x80)==0x00) { this._r.pc+=i; this._r.m++; this._r.t+=4; } },
            JRZn: function()  { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; if((this._r.f&0x80)==0x80) { this._r.pc+=i; this._r.m++; this._r.t+=4; } },
            JRNCn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; if((this._r.f&0x10)==0x00) { this._r.pc+=i; this._r.m++; this._r.t+=4; } },
            JRCn: function()  { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; if((this._r.f&0x10)==0x10) { this._r.pc+=i; this._r.m++; this._r.t+=4; } },

            DJNZn: function() { let i=MemoryInterfacing.rb(this._r.pc); if(i>127) i=-((~i+1)&255); this._r.pc++; this._r.m=2; this._r.t=8; this._r.b--; if(this._r.b) { this._r.pc+=i; this._r.m++; this._r.t+=4; } },

            CALLnn: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc+2); this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m=5; this._r.t=20; },
            CALLNZnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x80)==0x00) { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc+2); this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m+=2; this._r.t+=8; } else this._r.pc+=2; },
            CALLZnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x80)==0x80) { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc+2); this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m+=2; this._r.t+=8; } else this._r.pc+=2; },
            CALLNCnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x10)==0x00) { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc+2); this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m+=2; this._r.t+=8; } else this._r.pc+=2; },
            CALLCnn: function() { this._r.m=3; this._r.t=12; if((this._r.f&0x10)==0x10) { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc+2); this._r.pc=MemoryInterfacing.rw(this._r.pc); this._r.m+=2; this._r.t+=8; } else this._r.pc+=2; },

            RET: function() { this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m=3; this._r.t=12; },
            RETI: function() { this._r.ime=1; this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m=3; this._r.t=12; },
            RETNZ: function() { this._r.m=1; this._r.t=4; if((this._r.f&0x80)==0x00) { this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m+=2; this._r.t+=8; } },
            RETZ: function() { this._r.m=1; this._r.t=4; if((this._r.f&0x80)==0x80) { this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m+=2; this._r.t+=8; } },
            RETNC: function() { this._r.m=1; this._r.t=4; if((this._r.f&0x10)==0x00) { this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m+=2; this._r.t+=8; } },
            RETC: function() { this._r.m=1; this._r.t=4; if((this._r.f&0x10)==0x10) { this._r.pc=MemoryInterfacing.rw(this._r.sp); this._r.sp+=2; this._r.m+=2; this._r.t+=8; } },

            RST00: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x00; this._r.m=3; this._r.t=12; },
            RST08: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x08; this._r.m=3; this._r.t=12; },
            RST10: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x10; this._r.m=3; this._r.t=12; },
            RST18: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x18; this._r.m=3; this._r.t=12; },
            RST20: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x20; this._r.m=3; this._r.t=12; },
            RST28: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x28; this._r.m=3; this._r.t=12; },
            RST30: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x30; this._r.m=3; this._r.t=12; },
            RST38: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x38; this._r.m=3; this._r.t=12; },
            RST40: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x40; this._r.m=3; this._r.t=12; },
            RST48: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x48; this._r.m=3; this._r.t=12; },
            RST50: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x50; this._r.m=3; this._r.t=12; },
            RST58: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x58; this._r.m=3; this._r.t=12; },
            RST60: function() { this._r.sp-=2; MemoryInterfacing.ww(this._r.sp,this._r.pc); this._r.pc=0x60; this._r.m=3; this._r.t=12; },

            NOP: function() { this._r.m=1; this._r.t=4; },
            HALT: function() { this._halt=1; this._r.m=1; this._r.t=4; },

            DI: function() { this._r.ime=0; this._r.m=1; this._r.t=4; },
            EI: function() { this._r.ime=1; this._r.m=1; this._r.t=4; },

            /*--- Helper functions ---*/
            fz: function(i,as) { this._r.f=0; if(!(i&255)) this._r.f|=128; this._r.f|=as?0x40:0; },
            MAPcb: function() {
              let i=MemoryInterfacing.rb(this._r.pc); this._r.pc++;
              this._r.pc &= 65535;
              if(this._cbmap[i]) this._cbmap[i]();
              else alert(i);
            },

            XX: function() {
              /*Undefined map entry*/
              let opc = this._r.pc-1;
              alert('Unimplemented instruction at $'+opc.toString(16)+', stopping.');
              this._stop=1;
            }
        }
    }

    reset = () =>
    {
        this._r = {
            a: 0, b: 0, c: 0, d: 0, e: 0, h: 0, l: 0, f: 0,
            pc: 0, sp: 0, i: 0, r: 0,
            m: 0, t: 0
        };

        this._clock = { m: 0, t: 0};

        this._halt = 0;
        this._stop = 0;
        this._ime = 1;
    }

    exec = () => {
        this._r.r = (this._r.r+1) & 127;
        this._map[MemoryInterfacing.rb(this._r.pc++)]();
        this._r.pc &= 65535;
        this._clock.m += this._r.m; this._clock.t += this._r.t;
        if(MemoryInterfacing._inbios && this._r.pc == 0x0100) MemoryInterfacing._inbios=0;
    }

    dispatcher = () =>
    {
        let op = MemoryInterfacing.rb(this._r.pc++);        // Fetch instruction
        this._map[op]();                                    // Dispatch
        this._r.pc &= 65535;                                // Mask PC to 16 bits
        this._clock.m += this._r.m;                         // Add time to CPU clock
        this._clock.t += this._r.t;
    }
}

export default CPU;
